name: Cron Job

on:
  schedule:
    - cron: "30 8 * * 1-5" # Runs at 8:00 AM UTC. Adjust the cron schedule as needed.
    - cron: "30 14 * * 1-5" # Runs at 8:00 AM UTC. Adjust the cron schedule as needed.

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x # Specify the desired Python version
          
      - name: Install ipykernel
        run: python -m pip install ipykernel
        
      - name: Install Python 3.11 kernel
        run: |
          python -m ipykernel install --name python3.11 --display-name "Python 3.11" --user
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbconvert
          
      - name: Check available kernels
        run: |
          jupyter kernelspec list
          
      - name: Find Jupyter path
        id: find-jupyter
        run: |
          echo "JUPYTER_PATH=$(which jupyter)" >> $GITHUB_ENV
          
      - name: Run the Colab notebook
        run: |
          $JUPYTER_PATH nbconvert --execute --to html --ExecutePreprocessor.kernel_name=python3.11 ARIMA_Model_Predict_FX.ipynb
        
